package meta.model.types;

public enum OracleDataType {

	BFILE, BINARY_DOUBLE, BINARY_FLOAT, BLOB, CHAR, CHAR_VARYING, CHARACTER, CHARACTER_VARYING, CLOB, DATE, DEC, DECIMAL, DOUBLE_PRECISION, FLOAT, INT, INTEGER, INTERVAL_DAY, INTERVAL_YEAR, LONG, LONG_RAW, LONG_VARCHAR, NATIONAL_CHAR, NATIONAL_CHAR_VARYING, NATIONAL_CHARACTER, NATIONAL_CHARACTER_VARYING, NCHAR, NCHAR_VARYING, NCLOB, NUMBER, NUMERIC, NVARCHAR2, RAW, REAL, ROWID, SMALL_INT, TIMESTAMP, UROWID, VARCHAR, VARCHAR2;

}
